/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ludoGameSol from "./LudoGame.sol";
export type { ludoGameSol };
export type { Lock } from "./Lock";
export type { LudoToken } from "./LudoToken";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { IERC20 } from "./LudoGame.sol/IERC20";
export { IERC20__factory } from "./factories/LudoGame.sol/IERC20__factory";
export type { LudoGame } from "./LudoGame.sol/LudoGame";
export { LudoGame__factory } from "./factories/LudoGame.sol/LudoGame__factory";
export { LudoToken__factory } from "./factories/LudoToken__factory";
